// <auto-generated />
using BookMan.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookMan.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20201106042645_Addbook")]
    partial class Addbook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BookMan.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Authors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Authors = "Trump D.",
                            Description = "Đây là của Trump",
                            Name = "ASP.NET Core for dummy",
                            Publisher = "Washington",
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            Authors = "Putin V. D.",
                            Description = "Đây là của Putin",
                            Name = "Pro ASP.NET Core",
                            Publisher = "Moscow",
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Authors = "Obama B.",
                            Description = "Đây là của Obama",
                            Name = "ASP.NET Core Video Tutorial  ",
                            Publisher = "Washington",
                            Year = 2020
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
